# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/leo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
kuaidi100:
  url: https://sp0.baidu.com/9_Q4sjW91Qh3otqbppnN2DJv/pae/channel/data/asyncqury
  cb: jQuery110206239658217067707_1570247589740
  appid: 4001
zhongtong:
  url: https://hdgateway.zto.com/WayBill_GetDetail
yunda:
  url: http://membernew.yundasys.com:15116/opserver/ydmb/interface.do
  action: member.order.get_mail_info_batch
  appid: ydmb
  sort: desc